// packages/solid/src/UploadWidget.tsx
import { createSignal, Show, For, onMount } from "solid-js";
import type { JSX } from "solid-js";
import { formatBytes, type FileState, type UploadResult } from "@bunny.net/upload-core";
import { createBunnyUpload } from "./create-bunny-upload";

export interface UploadWidgetProps {
  endpoint?: string;
  accept?: string[];
  maxSize?: string | number;
  maxFiles?: number;
  onComplete?: (files: UploadResult[]) => void;
  onError?: (error: Error, file?: FileState) => void;
  autoUpload?: boolean;
  label?: string;
  trigger?: (props: { open: () => void }) => JSX.Element;
}

export function UploadWidget(props: UploadWidgetProps) {
  const [isOpen, setIsOpen] = createSignal(false);
  const [isDragOver, setIsDragOver] = createSignal(false);

  const { files, addFiles, removeFile, upload, reset, isUploading } =
    createBunnyUpload({
      get endpoint() { return props.endpoint; },
      get accept() { return props.accept; },
      get maxSize() { return props.maxSize; },
      get maxFiles() { return props.maxFiles; },
      onComplete: (f) => props.onComplete?.(f),
      onError: (e, f) => props.onError?.(e, f),
    });

  let inputRef!: HTMLInputElement;
  let dialogRef!: HTMLDialogElement;

  const label = () => props.label ?? "Upload files";
  const autoUpload = () => props.autoUpload !== false;
  const allComplete = () =>
    files().length > 0 && files().every((f) => f.status === "complete");

  const open = () => {
    setIsOpen(true);
  };

  const close = () => {
    setIsOpen(false);
    reset();
    dialogRef?.close();
  };

  const handleFiles = (fileList: FileList | File[]) => {
    addFiles(fileList);
    if (autoUpload()) {
      queueMicrotask(() => upload());
    }
  };

  const onDrop = (e: DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    if (e.dataTransfer?.files.length) {
      handleFiles(e.dataTransfer.files);
    }
  };

  const onInputChange = (e: Event) => {
    const input = e.target as HTMLInputElement;
    if (input.files?.length) {
      handleFiles(input.files);
      input.value = "";
    }
  };

  return (
    <div style={{ display: "contents" }}>
      {props.trigger ? (
        props.trigger({ open })
      ) : (
        <button type="button" class="bunny-widget-trigger" onClick={open}>
          {label()}
        </button>
      )}

      <Show when={isOpen()}>
        <dialog
          ref={(el) => {
            dialogRef = el;
            // showModal on next microtask after DOM insertion
            queueMicrotask(() => el.showModal());
          }}
          class="bunny-widget-dialog"
          onClose={close}
          onClick={(e) => {
            if (e.target === dialogRef) close();
          }}
          aria-modal="true"
          aria-label={label()}
        >
          <div class="bunny-widget">
            <div class="bunny-widget-header">
              <span class="bunny-widget-title">{label()}</span>
              <button
                type="button"
                class="bunny-widget-close"
                onClick={close}
                aria-label="Close"
              >
                &times;
              </button>
            </div>

            <div
              class={`bunny-widget-dropzone ${isDragOver() ? "bunny-widget-dropzone--active" : ""}`}
              onDrop={onDrop}
              onDragOver={(e) => {
                e.preventDefault();
                setIsDragOver(true);
              }}
              onDragLeave={(e) => {
                e.preventDefault();
                setIsDragOver(false);
              }}
              onClick={() => inputRef?.click()}
              role="button"
              tabIndex={0}
              aria-label="Drop files here or click to browse"
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") inputRef?.click();
              }}
            >
              <input
                ref={inputRef!}
                type="file"
                multiple={props.maxFiles !== 1}
                accept={props.accept?.join(",")}
                onChange={onInputChange}
                style={{ display: "none" }}
              />
              <p class="bunny-widget-dropzone-text">
                {isDragOver()
                  ? "Drop to upload"
                  : "Drop files here or click to browse"}
              </p>
              <Show when={props.maxSize != null}>
                <p class="bunny-widget-hint">
                  Max{" "}
                  {typeof props.maxSize === "string"
                    ? props.maxSize
                    : formatBytes(props.maxSize as number)}
                  {props.maxFiles
                    ? ` · ${props.maxFiles} file${props.maxFiles > 1 ? "s" : ""}`
                    : ""}
                </p>
              </Show>
            </div>

            <Show when={files().length > 0}>
              <ul class="bunny-widget-file-list" aria-live="polite">
                <For each={files()}>
                  {(file) => (
                    <li class={`bunny-widget-file bunny-widget-file--${file.status}`}>
                      <span class="bunny-widget-file-name">{file.name}</span>
                      <span class="bunny-widget-file-size">
                        {formatBytes(file.size)}
                      </span>

                      <Show when={file.status === "uploading"}>
                        <div
                          class="bunny-widget-progress"
                          role="progressbar"
                          aria-valuenow={Math.round(file.progress)}
                          aria-valuemin={0}
                          aria-valuemax={100}
                          aria-label={`Uploading ${file.name}`}
                        >
                          <div
                            class="bunny-widget-progress-bar"
                            style={{ width: `${file.progress}%` }}
                          />
                        </div>
                      </Show>

                      <Show when={file.status === "complete"}>
                        <span class="bunny-widget-file-complete">✓</span>
                      </Show>

                      <Show when={file.status === "error"}>
                        <span class="bunny-widget-file-error">
                          {file.error ?? "Failed"}
                        </span>
                      </Show>

                      <Show
                        when={
                          file.status === "idle" || file.status === "error"
                        }
                      >
                        <button
                          class="bunny-widget-file-remove"
                          onClick={() => removeFile(file.id)}
                          aria-label={`Remove ${file.name}`}
                        >
                          &times;
                        </button>
                      </Show>
                    </li>
                  )}
                </For>
              </ul>
            </Show>

            <div class="bunny-widget-footer">
              <Show
                when={
                  !autoUpload() &&
                  files().some((f) => f.status === "idle")
                }
              >
                <button
                  type="button"
                  class="bunny-widget-upload"
                  onClick={() => upload()}
                  disabled={isUploading()}
                >
                  {isUploading() ? "Uploading..." : "Upload"}
                </button>
              </Show>
              <Show when={allComplete()}>
                <button
                  type="button"
                  class="bunny-widget-done"
                  onClick={close}
                >
                  Done
                </button>
              </Show>
            </div>
          </div>
        </dialog>
      </Show>
    </div>
  );
}

// packages/angular/src/upload-widget.component.ts
import {
  Component,
  input,
  output,
  computed,
  inject,
  signal,
  OnInit,
  ViewChild,
  ElementRef,
  AfterViewInit,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { formatBytes, type UploadResult } from "@bunny.net/upload-core";
import { BunnyUploadService } from "./bunny-upload.service";

@Component({
  selector: "bunny-upload-widget",
  standalone: true,
  imports: [CommonModule],
  providers: [BunnyUploadService],
  template: `
    <ng-content select="[trigger]">
      <button type="button" class="bunny-widget-trigger" (click)="open()">
        {{ label() }}
      </button>
    </ng-content>

    @if (isOpen()) {
      <dialog
        #dialog
        class="bunny-widget-dialog"
        (close)="close()"
        (click)="onBackdropClick($event)"
      >
        <div class="bunny-widget">
          <div class="bunny-widget-header">
            <span class="bunny-widget-title">{{ label() }}</span>
            <button type="button" class="bunny-widget-close" (click)="close()" aria-label="Close">
              &times;
            </button>
          </div>

          <div
            class="bunny-widget-dropzone"
            [class.bunny-widget-dropzone--active]="isDragOver()"
            (drop)="onDrop($event)"
            (dragover)="onDragOver($event)"
            (dragleave)="onDragLeave($event)"
            (click)="fileInput.click()"
            (keydown.enter)="fileInput.click()"
            (keydown.space)="fileInput.click()"
            role="button"
            tabindex="0"
          >
            <input
              #fileInput
              type="file"
              [multiple]="maxFiles() !== 1"
              [accept]="acceptString()"
              (change)="onFileChange($event)"
              hidden
            />
            <p class="bunny-widget-dropzone-text">
              {{ isDragOver() ? "Drop to upload" : "Drop files here or click to browse" }}
            </p>
            @if (maxSize()) {
              <p class="bunny-widget-hint">
                Max {{ maxSize() }}@if (maxFiles()) { &middot; {{ maxFiles() }} file{{ maxFiles()! > 1 ? "s" : "" }}}
              </p>
            }
          </div>

          @if (uploadService.files().length > 0) {
            <ul class="bunny-widget-file-list">
              @for (file of uploadService.files(); track file.id) {
                <li class="bunny-widget-file" [class]="'bunny-widget-file--' + file.status">
                  <span class="bunny-widget-file-name">{{ file.name }}</span>
                  <span class="bunny-widget-file-size">{{ formatFileSize(file.size) }}</span>
                  @if (file.status === "uploading") {
                    <div class="bunny-widget-progress">
                      <div class="bunny-widget-progress-bar" [style.width.%]="file.progress"></div>
                    </div>
                  }
                  @if (file.status === "complete") {
                    <span class="bunny-widget-file-complete">&#10003;</span>
                  }
                  @if (file.status === "error") {
                    <span class="bunny-widget-file-error">{{ file.error ?? "Failed" }}</span>
                  }
                  @if (file.status === "idle" || file.status === "error") {
                    <button
                      class="bunny-widget-file-remove"
                      (click)="uploadService.removeFile(file.id)"
                      [attr.aria-label]="'Remove ' + file.name"
                    >&times;</button>
                  }
                </li>
              }
            </ul>
          }

          <div class="bunny-widget-footer">
            @if (!autoUpload() && hasIdleFiles()) {
              <button
                type="button"
                class="bunny-widget-upload"
                (click)="doUpload()"
                [disabled]="uploadService.isUploading()"
              >
                {{ uploadService.isUploading() ? "Uploading..." : "Upload" }}
              </button>
            }
            @if (allComplete()) {
              <button type="button" class="bunny-widget-done" (click)="close()">
                Done
              </button>
            }
          </div>
        </div>
      </dialog>
    }
  `,
})
export class UploadWidgetComponent implements OnInit {
  readonly endpoint = input<string>();
  readonly accept = input<string[]>();
  readonly maxSize = input<string | number>();
  readonly maxFiles = input<number>();
  readonly autoUpload = input(true);
  readonly label = input("Upload files");

  readonly completed = output<UploadResult[]>();
  readonly errored = output<Error>();

  @ViewChild("dialog") dialogEl?: ElementRef<HTMLDialogElement>;

  uploadService = inject(BunnyUploadService);

  isOpen = signal(false);
  isDragOver = signal(false);

  readonly allComplete = computed(
    () =>
      this.uploadService.files().length > 0 &&
      this.uploadService.files().every((f) => f.status === "complete")
  );

  ngOnInit() {
    this.uploadService.configure({
      endpoint: this.endpoint(),
      restrictions: {
        allowedTypes: this.accept(),
        maxFileSize: this.maxSize(),
        maxFiles: this.maxFiles(),
      },
    });
  }

  acceptString(): string {
    return this.accept()?.join(",") ?? "";
  }

  hasIdleFiles(): boolean {
    return this.uploadService.files().some((f) => f.status === "idle");
  }

  formatFileSize(bytes: number): string {
    return formatBytes(bytes);
  }

  open() {
    this.isOpen.set(true);
    // Use setTimeout to wait for dialog element to be rendered
    setTimeout(() => this.dialogEl?.nativeElement.showModal());
  }

  close() {
    this.isOpen.set(false);
    this.uploadService.reset();
  }

  onBackdropClick(event: MouseEvent) {
    if (event.target === this.dialogEl?.nativeElement) {
      this.close();
    }
  }

  onDragOver(event: DragEvent) {
    event.preventDefault();
    this.isDragOver.set(true);
  }

  onDragLeave(event: DragEvent) {
    event.preventDefault();
    this.isDragOver.set(false);
  }

  onDrop(event: DragEvent) {
    event.preventDefault();
    this.isDragOver.set(false);
    if (event.dataTransfer?.files.length) {
      this.handleFiles(event.dataTransfer.files);
    }
  }

  onFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files?.length) {
      this.handleFiles(input.files);
      input.value = "";
    }
  }

  async doUpload() {
    const results = await this.uploadService.upload();
    if (results.length > 0) {
      this.completed.emit(results);
    }
  }

  private async handleFiles(fileList: FileList) {
    this.uploadService.addFiles(fileList);
    if (this.autoUpload()) {
      const results = await this.uploadService.upload();
      if (results.length > 0) {
        this.completed.emit(results);
      }
    }
  }
}

<ng-content select="[trigger]">
  <button type="button" class="bunny-widget-trigger" (click)="open()">
    {{ label() }}
  </button>
</ng-content>

@if (isOpen()) {
  <dialog
    #dialog
    class="bunny-widget-dialog"
    (close)="close()"
    (click)="onBackdropClick($event)"
    aria-modal="true"
    [attr.aria-label]="label()"
  >
    <div class="bunny-widget">
      <div class="bunny-widget-header">
        <span class="bunny-widget-title">{{ label() }}</span>
        <button type="button" class="bunny-widget-close" (click)="close()" aria-label="Close">
          &times;
        </button>
      </div>

      <div
        class="bunny-widget-dropzone"
        [class.bunny-widget-dropzone--active]="isDragOver()"
        (drop)="onDrop($event)"
        (dragover)="onDragOver($event)"
        (dragleave)="onDragLeave($event)"
        (click)="fileInput.click()"
        (keydown.enter)="fileInput.click()"
        (keydown.space)="fileInput.click()"
        role="button"
        tabindex="0"
        aria-label="Drop files here or click to browse"
      >
        <input
          #fileInput
          type="file"
          [multiple]="maxFiles() !== 1"
          [accept]="acceptString()"
          (change)="onFileChange($event)"
          hidden
        />
        <p class="bunny-widget-dropzone-text">
          {{ isDragOver() ? "Drop to upload" : "Drop files here or click to browse" }}
        </p>
        @if (maxSize()) {
          <p class="bunny-widget-hint">
            Max {{ maxSize() }}@if (maxFiles()) { &middot; {{ maxFiles() }} file{{ maxFiles()! > 1 ? "s" : "" }}}
          </p>
        }
      </div>

      @if (uploadService.files().length > 0) {
        <ul class="bunny-widget-file-list" aria-live="polite">
          @for (file of uploadService.files(); track file.id) {
            <li class="bunny-widget-file" [class]="'bunny-widget-file--' + file.status">
              <span class="bunny-widget-file-name">{{ file.name }}</span>
              <span class="bunny-widget-file-size">{{ formatFileSize(file.size) }}</span>
              @if (file.status === "uploading") {
                <div class="bunny-widget-progress"
                  role="progressbar"
                  [attr.aria-valuenow]="file.progress | number:'1.0-0'"
                  aria-valuemin="0"
                  aria-valuemax="100"
                  [attr.aria-label]="'Uploading ' + file.name"
                >
                  <div class="bunny-widget-progress-bar" [style.width.%]="file.progress"></div>
                </div>
              }
              @if (file.status === "complete") {
                <span class="bunny-widget-file-complete">&#10003;</span>
              }
              @if (file.status === "error") {
                <span class="bunny-widget-file-error" role="alert">{{ file.error ?? "Failed" }}</span>
              }
              @if (file.status === "idle" || file.status === "error") {
                <button
                  class="bunny-widget-file-remove"
                  (click)="uploadService.removeFile(file.id)"
                  [attr.aria-label]="'Remove ' + file.name"
                >&times;</button>
              }
            </li>
          }
        </ul>
      }

      <div class="bunny-widget-footer">
        @if (!autoUpload() && hasIdleFiles()) {
          <button
            type="button"
            class="bunny-widget-upload"
            (click)="doUpload()"
            [disabled]="uploadService.isUploading()"
          >
            {{ uploadService.isUploading() ? "Uploading..." : "Upload" }}
          </button>
        }
        @if (allComplete()) {
          <button type="button" class="bunny-widget-done" (click)="close()">
            Done
          </button>
        }
      </div>
    </div>
  </dialog>
}
