// packages/react/src/upload-file-list.tsx
import type { FileState } from "@bunny.net/upload-core";
import { formatBytes } from "@bunny.net/upload-core";

export interface UploadFileListProps {
  files: FileState[];
  onRemove?: (id: string) => void;
  onRetry?: () => void;
  className?: string;
}

export function UploadFileList({
  files,
  onRemove,
  onRetry,
  className,
}: UploadFileListProps) {
  if (files.length === 0) return null;

  return (
    <ul className={`bunny-upload-file-list ${className ?? ""}`.trim()} aria-live="polite">
      {files.map((file) => (
        <li
          key={file.id}
          className={`bunny-upload-file bunny-upload-file--${file.status}`}
        >
          <div className="bunny-upload-file-info">
            <span className="bunny-upload-file-name">{file.name}</span>
            <span className="bunny-upload-file-size">
              {formatBytes(file.size)}
            </span>
          </div>

          {file.status === "uploading" && (
            <div
              className="bunny-upload-progress"
              role="progressbar"
              aria-valuenow={Math.round(file.progress)}
              aria-valuemin={0}
              aria-valuemax={100}
              aria-label={`Uploading ${file.name}`}
            >
              <div
                className="bunny-upload-progress-bar"
                style={{ width: `${file.progress}%` }}
              />
            </div>
          )}

          {file.status === "error" && (
            <div className="bunny-upload-file-error" role="alert">
              <span>{file.error}</span>
              {onRetry && (
                <button className="bunny-upload-retry" onClick={onRetry}>
                  Retry
                </button>
              )}
            </div>
          )}

          {file.status === "complete" && (
            <span className="bunny-upload-file-complete">Uploaded</span>
          )}

          {onRemove && (file.status === "idle" || file.status === "error") && (
            <button
              className="bunny-upload-remove"
              onClick={() => onRemove(file.id)}
              aria-label={`Remove ${file.name}`}
            >
              &times;
            </button>
          )}
        </li>
      ))}
    </ul>
  );
}

// packages/angular/src/upload-file-list.component.ts
import { Component, input, output } from "@angular/core";
import { CommonModule } from "@angular/common";
import { formatBytes, type FileState } from "@bunny.net/upload-core";

@Component({
  selector: "bunny-upload-file-list",
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (files().length > 0) {
      <ul class="bunny-upload-file-list">
        @for (file of files(); track file.id) {
          <li class="bunny-upload-file" [class]="'bunny-upload-file--' + file.status">
            <div class="bunny-upload-file-info">
              <span class="bunny-upload-file-name">{{ file.name }}</span>
              <span class="bunny-upload-file-size">{{ formatFileSize(file.size) }}</span>
            </div>
            @if (file.status === "uploading") {
              <div class="bunny-upload-progress">
                <div class="bunny-upload-progress-bar" [style.width.%]="file.progress"></div>
              </div>
            }
            @if (file.status === "error") {
              <div class="bunny-upload-file-error">
                <span>{{ file.error }}</span>
                <button class="bunny-upload-retry" (click)="retry.emit()">Retry</button>
              </div>
            }
            @if (file.status === "complete") {
              <span class="bunny-upload-file-complete">Uploaded</span>
            }
            @if (file.status === "idle" || file.status === "error") {
              <button
                class="bunny-upload-remove"
                (click)="remove.emit(file.id)"
                [attr.aria-label]="'Remove ' + file.name"
              >&times;</button>
            }
          </li>
        }
      </ul>
    }
  `,
})
export class UploadFileListComponent {
  readonly files = input.required<FileState[]>();
  readonly remove = output<string>();
  readonly retry = output<void>();

  formatFileSize(bytes: number): string {
    return formatBytes(bytes);
  }
}

@if (files().length > 0) {
  <ul class="bunny-upload-file-list">
    @for (file of files(); track file.id) {
      <li class="bunny-upload-file" [class]="'bunny-upload-file--' + file.status">
        <div class="bunny-upload-file-info">
          <span class="bunny-upload-file-name">{{ file.name }}</span>
          <span class="bunny-upload-file-size">{{ formatFileSize(file.size) }}</span>
        </div>
        @if (file.status === "uploading") {
          <div class="bunny-upload-progress"
            role="progressbar"
            [attr.aria-valuenow]="file.progress | number:'1.0-0'"
            aria-valuemin="0"
            aria-valuemax="100"
            [attr.aria-label]="'Uploading ' + file.name"
          >
            <div class="bunny-upload-progress-bar" [style.width.%]="file.progress"></div>
          </div>
        }
        @if (file.status === "error") {
          <div class="bunny-upload-file-error" role="alert">
            <span>{{ file.error }}</span>
            <button class="bunny-upload-retry" (click)="retry.emit()">Retry</button>
          </div>
        }
        @if (file.status === "complete") {
          <span class="bunny-upload-file-complete">Uploaded</span>
        }
        @if (file.status === "idle" || file.status === "error") {
          <button
            class="bunny-upload-remove"
            (click)="remove.emit(file.id)"
            [attr.aria-label]="'Remove ' + file.name"
          >&times;</button>
        }
      </li>
    }
  </ul>
}
