// packages/angular/src/bunny-upload.component.ts
import {
  Component,
  input,
  output,
  inject,
  OnInit,
  ViewChild,
  ElementRef,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { formatBytes, type UploadResult } from "@bunny.net/upload-core";
import { BunnyUploadService } from "./bunny-upload.service";

@Component({
  selector: "bunny-upload",
  standalone: true,
  imports: [CommonModule],
  providers: [BunnyUploadService],
  templateUrl: "./bunny-upload.component.html",
})
export class BunnyUploadComponent implements OnInit {
  readonly endpoint = input<string>();
  readonly accept = input<string[]>();
  readonly maxSize = input<string | number>();
  readonly maxFiles = input<number>();
  readonly autoUpload = input(true);
  readonly className = input("");

  readonly completed = output<UploadResult[]>();
  readonly errored = output<Error>();

  @ViewChild("fileInput") fileInput!: ElementRef<HTMLInputElement>;

  uploadService = inject(BunnyUploadService);
  isDragOver = false;

  ngOnInit() {
    this.uploadService.configure({
      endpoint: this.endpoint(),
      restrictions: {
        allowedTypes: this.accept(),
        maxFileSize: this.maxSize(),
        maxFiles: this.maxFiles(),
      },
    });
  }

  acceptString(): string {
    return this.accept()?.join(",") ?? "";
  }

  hasIdleFiles(): boolean {
    return this.uploadService.files().some((f) => f.status === "idle");
  }

  formatFileSize(bytes: number): string {
    return formatBytes(bytes);
  }

  onDragOver(event: DragEvent) {
    event.preventDefault();
    this.isDragOver = true;
  }

  onDrop(event: DragEvent) {
    event.preventDefault();
    this.isDragOver = false;
    if (event.dataTransfer?.files.length) {
      this.handleFiles(event.dataTransfer.files);
    }
  }

  onFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files?.length) {
      this.handleFiles(input.files);
      input.value = "";
    }
  }

  async retry() {
    const results = await this.uploadService.upload();
    if (results.length > 0) {
      this.completed.emit(results);
    }
  }

  private async handleFiles(fileList: FileList) {
    this.uploadService.addFiles(fileList);
    if (this.autoUpload()) {
      const results = await this.uploadService.upload();
      if (results.length > 0) {
        this.completed.emit(results);
      }
    }
  }
}

<div class="bunny-upload" [class]="className()">
  <div
    class="bunny-upload-dropzone"
    [class.bunny-upload-dropzone--active]="isDragOver"
    (drop)="onDrop($event)"
    (dragover)="onDragOver($event)"
    (dragleave)="isDragOver = false"
    (click)="fileInput.click()"
    (keydown.enter)="fileInput.click()"
    (keydown.space)="fileInput.click()"
    role="button"
    tabindex="0"
  >
    <input
      #fileInput
      type="file"
      [multiple]="maxFiles() !== 1"
      [accept]="acceptString()"
      (change)="onFileChange($event)"
      hidden
    />
    <div class="bunny-upload-dropzone-text">
      <p>Drop files here or click to browse</p>
      @if (maxSize()) {
        <p class="bunny-upload-hint">Max size: {{ maxSize() }}</p>
      }
    </div>
  </div>

  @if (uploadService.files().length > 0) {
    <ul class="bunny-upload-file-list">
      @for (file of uploadService.files(); track file.id) {
        <li
          class="bunny-upload-file"
          [class]="'bunny-upload-file--' + file.status"
        >
          <div class="bunny-upload-file-info">
            <span class="bunny-upload-file-name">{{ file.name }}</span>
            <span class="bunny-upload-file-size">{{
              formatFileSize(file.size)
            }}</span>
          </div>

          @if (file.status === "uploading") {
            <div class="bunny-upload-progress">
              <div
                class="bunny-upload-progress-bar"
                [style.width.%]="file.progress"
              ></div>
            </div>
          }

          @if (file.status === "error") {
            <div class="bunny-upload-file-error">
              <span>{{ file.error }}</span>
              <button class="bunny-upload-retry" (click)="retry()">
                Retry
              </button>
            </div>
          }

          @if (file.status === "complete") {
            <span class="bunny-upload-file-complete">Uploaded</span>
          }

          @if (file.status === "idle" || file.status === "error") {
            <button
              class="bunny-upload-remove"
              (click)="uploadService.removeFile(file.id)"
              [attr.aria-label]="'Remove ' + file.name"
            >
              &times;
            </button>
          }
        </li>
      }
    </ul>
  }

  @if (!autoUpload() && hasIdleFiles()) {
    <button
      class="bunny-upload-button"
      (click)="retry()"
      [disabled]="uploadService.isUploading()"
    >
      {{ uploadService.isUploading() ? "Uploading..." : "Upload" }}
    </button>
  }
</div>

// packages/react/src/bunny-upload.tsx
import React, { useCallback, useRef, useState } from "react";
import type { FileState, UploadResult } from "@bunny.net/upload-core";
import { formatBytes } from "@bunny.net/upload-core";
import { useBunnyUpload } from "./use-bunny-upload";

export interface BunnyUploadProps {
  endpoint?: string;
  accept?: string[];
  maxSize?: string | number;
  maxFiles?: number;
  onComplete?: (files: UploadResult[]) => void;
  onError?: (error: Error, file?: FileState) => void;
  className?: string;
  autoUpload?: boolean;
}

export function BunnyUpload({
  endpoint,
  accept,
  maxSize,
  maxFiles,
  onComplete,
  onError,
  className,
  autoUpload = true,
}: BunnyUploadProps) {
  const { files, addFiles, removeFile, upload, isUploading } = useBunnyUpload({
    endpoint,
    accept,
    maxSize,
    maxFiles,
    onComplete,
    onError,
  });

  const inputRef = useRef<HTMLInputElement>(null);
  const [isDragOver, setIsDragOver] = useState(false);

  const handleFiles = useCallback(
    (fileList: FileList | File[]) => {
      addFiles(fileList);
      if (autoUpload) {
        // Allow state to update before uploading
        queueMicrotask(() => upload());
      }
    },
    [addFiles, autoUpload, upload]
  );

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragOver(false);
      if (e.dataTransfer.files.length > 0) {
        handleFiles(e.dataTransfer.files);
      }
    },
    [handleFiles]
  );

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
  }, []);

  const handleClick = useCallback(() => {
    inputRef.current?.click();
  }, []);

  const handleInputChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.files && e.target.files.length > 0) {
        handleFiles(e.target.files);
        e.target.value = "";
      }
    },
    [handleFiles]
  );

  const acceptString = accept?.join(",");

  return (
    <div className={`bunny-upload ${className ?? ""}`.trim()}>
      <div
        className={`bunny-upload-dropzone ${isDragOver ? "bunny-upload-dropzone--active" : ""}`}
        onDrop={handleDrop}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onClick={handleClick}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") handleClick();
        }}
      >
        <input
          ref={inputRef}
          type="file"
          multiple={maxFiles !== 1}
          accept={acceptString}
          onChange={handleInputChange}
          style={{ display: "none" }}
        />
        <div className="bunny-upload-dropzone-text">
          <p>Drop files here or click to browse</p>
          {maxSize && (
            <p className="bunny-upload-hint">
              Max size: {typeof maxSize === "string" ? maxSize : formatBytes(maxSize)}
            </p>
          )}
        </div>
      </div>

      {files.length > 0 && (
        <ul className="bunny-upload-file-list">
          {files.map((file) => (
            <FileItem
              key={file.id}
              file={file}
              onRemove={removeFile}
              onRetry={() => upload()}
            />
          ))}
        </ul>
      )}

      {!autoUpload && files.some((f) => f.status === "idle") && (
        <button
          className="bunny-upload-button"
          onClick={() => upload()}
          disabled={isUploading}
        >
          {isUploading ? "Uploading..." : "Upload"}
        </button>
      )}
    </div>
  );
}

function FileItem({
  file,
  onRemove,
  onRetry,
}: {
  file: FileState;
  onRemove: (id: string) => void;
  onRetry: () => void;
}) {
  return (
    <li className={`bunny-upload-file bunny-upload-file--${file.status}`}>
      <div className="bunny-upload-file-info">
        <span className="bunny-upload-file-name">{file.name}</span>
        <span className="bunny-upload-file-size">{formatBytes(file.size)}</span>
      </div>

      {file.status === "uploading" && (
        <div className="bunny-upload-progress">
          <div
            className="bunny-upload-progress-bar"
            style={{ width: `${file.progress}%` }}
          />
        </div>
      )}

      {file.status === "error" && (
        <div className="bunny-upload-file-error">
          <span>{file.error}</span>
          <button
            className="bunny-upload-retry"
            onClick={onRetry}
          >
            Retry
          </button>
        </div>
      )}

      {file.status === "complete" && (
        <span className="bunny-upload-file-complete">Uploaded</span>
      )}

      {(file.status === "idle" || file.status === "error") && (
        <button
          className="bunny-upload-remove"
          onClick={() => onRemove(file.id)}
          aria-label={`Remove ${file.name}`}
        >
          &times;
        </button>
      )}
    </li>
  );
}
