// packages/solid/src/UploadDropzone.tsx
import { createSignal } from "solid-js";
import type { JSX } from "solid-js";
import type { FileState, UploadResult } from "@bunny.net/upload-core";
import { createBunnyUpload } from "./create-bunny-upload";

export interface UploadDropzoneRenderProps {
  isDragOver: () => boolean;
  openFilePicker: () => void;
  files: () => FileState[];
  removeFile: (id: string) => void;
  upload: () => Promise<UploadResult[]>;
  reset: () => void;
  isUploading: () => boolean;
  getDropzoneProps: () => {
    onDrop: (e: DragEvent) => void;
    onDragOver: (e: DragEvent) => void;
    onDragLeave: (e: DragEvent) => void;
  };
  getInputProps: () => {
    ref: (el: HTMLInputElement) => void;
    type: "file";
    multiple: boolean;
    accept: string | undefined;
    onChange: (e: Event) => void;
    style: { display: "none" };
  };
}

export interface UploadDropzoneProps {
  endpoint?: string;
  accept?: string[];
  maxSize?: string | number;
  maxFiles?: number;
  presigned?: boolean;
  autoUpload?: boolean;
  onComplete?: (files: UploadResult[]) => void;
  onError?: (error: Error, file?: FileState) => void;
  children: (props: UploadDropzoneRenderProps) => JSX.Element;
}

export function UploadDropzone(props: UploadDropzoneProps) {
  const { files, addFiles, removeFile, upload, reset, isUploading } =
    createBunnyUpload({
      get endpoint() { return props.endpoint; },
      get accept() { return props.accept; },
      get maxSize() { return props.maxSize; },
      get maxFiles() { return props.maxFiles; },
      get presigned() { return props.presigned; },
      onComplete: (f) => props.onComplete?.(f),
      onError: (e, f) => props.onError?.(e, f),
    });

  let inputRef!: HTMLInputElement;
  const [isDragOver, setIsDragOver] = createSignal(false);

  const handleFiles = (fileList: FileList | File[]) => {
    addFiles(fileList);
    if (props.autoUpload !== false) {
      queueMicrotask(() => upload());
    }
  };

  const getDropzoneProps = () => ({
    onDrop: (e: DragEvent) => {
      e.preventDefault();
      setIsDragOver(false);
      if (e.dataTransfer?.files.length) {
        handleFiles(e.dataTransfer.files);
      }
    },
    onDragOver: (e: DragEvent) => {
      e.preventDefault();
      setIsDragOver(true);
    },
    onDragLeave: (e: DragEvent) => {
      e.preventDefault();
      setIsDragOver(false);
    },
  });

  const getInputProps = () => ({
    ref: (el: HTMLInputElement) => {
      inputRef = el;
    },
    type: "file" as const,
    multiple: props.maxFiles !== 1,
    accept: props.accept?.join(","),
    onChange: (e: Event) => {
      const input = e.target as HTMLInputElement;
      if (input.files?.length) {
        handleFiles(input.files);
        input.value = "";
      }
    },
    style: { display: "none" as const },
  });

  const openFilePicker = () => inputRef?.click();

  return (
    <>
      {props.children({
        isDragOver,
        openFilePicker,
        files,
        removeFile,
        upload,
        reset,
        isUploading,
        getDropzoneProps,
        getInputProps,
      })}
    </>
  );
}

// packages/react/src/upload-dropzone.tsx
import React, { useCallback, useRef, useState } from "react";
import type { FileState, UploadResult } from "@bunny.net/upload-core";
import { useBunnyUpload } from "./use-bunny-upload";

export interface UploadDropzoneRenderProps {
  /** Whether a file is being dragged over the dropzone */
  isDragOver: boolean;
  /** Open the native file picker */
  openFilePicker: () => void;
  /** Current file states */
  files: FileState[];
  /** Remove a file by ID */
  removeFile: (id: string) => void;
  /** Manually trigger upload (when autoUpload is false) */
  upload: () => Promise<UploadResult[]>;
  /** Reset all files */
  reset: () => void;
  /** Whether any file is currently uploading */
  isUploading: boolean;
  /** Props to spread onto your dropzone container element */
  getDropzoneProps: () => {
    onDrop: (e: React.DragEvent) => void;
    onDragOver: (e: React.DragEvent) => void;
    onDragLeave: (e: React.DragEvent) => void;
  };
  /** Props to spread onto a hidden file input */
  getInputProps: () => {
    ref: React.RefObject<HTMLInputElement | null>;
    type: "file";
    multiple: boolean;
    accept: string | undefined;
    onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    style: { display: "none" };
  };
}

export interface UploadDropzoneProps {
  endpoint?: string;
  accept?: string[];
  maxSize?: string | number;
  maxFiles?: number;
  presigned?: boolean;
  autoUpload?: boolean;
  onComplete?: (files: UploadResult[]) => void;
  onError?: (error: Error, file?: FileState) => void;
  children: (props: UploadDropzoneRenderProps) => React.ReactNode;
}

export function UploadDropzone({
  endpoint,
  accept,
  maxSize,
  maxFiles,
  presigned,
  autoUpload = true,
  onComplete,
  onError,
  children,
}: UploadDropzoneProps) {
  const { files, addFiles, removeFile, upload, reset, isUploading } =
    useBunnyUpload({
      endpoint,
      accept,
      maxSize,
      maxFiles,
      presigned,
      onComplete,
      onError,
    });

  const inputRef = useRef<HTMLInputElement>(null);
  const [isDragOver, setIsDragOver] = useState(false);

  const handleFiles = useCallback(
    (fileList: FileList | File[]) => {
      addFiles(fileList);
      if (autoUpload) {
        queueMicrotask(() => upload());
      }
    },
    [addFiles, autoUpload, upload]
  );

  const getDropzoneProps = useCallback(
    () => ({
      onDrop: (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragOver(false);
        if (e.dataTransfer.files.length > 0) {
          handleFiles(e.dataTransfer.files);
        }
      },
      onDragOver: (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragOver(true);
      },
      onDragLeave: (e: React.DragEvent) => {
        e.preventDefault();
        setIsDragOver(false);
      },
    }),
    [handleFiles]
  );

  const getInputProps = useCallback(
    () => ({
      ref: inputRef,
      type: "file" as const,
      multiple: maxFiles !== 1,
      accept: accept?.join(","),
      onChange: (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files.length > 0) {
          handleFiles(e.target.files);
          e.target.value = "";
        }
      },
      style: { display: "none" as const },
    }),
    [accept, maxFiles, handleFiles]
  );

  const openFilePicker = useCallback(() => {
    inputRef.current?.click();
  }, []);

  return (
    <>
      {children({
        isDragOver,
        openFilePicker,
        files,
        removeFile,
        upload,
        reset,
        isUploading,
        getDropzoneProps,
        getInputProps,
      })}
    </>
  );
}
