// packages/solid/src/UploadWidget.tsx
import { createSignal, Show, For, onMount } from "solid-js";
import type { JSX } from "solid-js";
import { formatBytes, type FileState, type UploadResult } from "@bunny.net/upload-core";
import { createBunnyUpload } from "./create-bunny-upload";

export interface UploadWidgetProps {
  endpoint?: string;
  accept?: string[];
  maxSize?: string | number;
  maxFiles?: number;
  onComplete?: (files: UploadResult[]) => void;
  onError?: (error: Error, file?: FileState) => void;
  autoUpload?: boolean;
  label?: string;
  trigger?: (props: { open: () => void }) => JSX.Element;
}

export function UploadWidget(props: UploadWidgetProps) {
  const [isOpen, setIsOpen] = createSignal(false);
  const [isDragOver, setIsDragOver] = createSignal(false);

  const { files, addFiles, removeFile, upload, reset, isUploading } =
    createBunnyUpload({
      get endpoint() { return props.endpoint; },
      get accept() { return props.accept; },
      get maxSize() { return props.maxSize; },
      get maxFiles() { return props.maxFiles; },
      onComplete: (f) => props.onComplete?.(f),
      onError: (e, f) => props.onError?.(e, f),
    });

  let inputRef!: HTMLInputElement;
  let dialogRef!: HTMLDialogElement;

  const label = () => props.label ?? "Upload files";
  const autoUpload = () => props.autoUpload !== false;
  const allComplete = () =>
    files().length > 0 && files().every((f) => f.status === "complete");

  const open = () => {
    setIsOpen(true);
  };

  const close = () => {
    setIsOpen(false);
    reset();
    dialogRef?.close();
  };

  const handleFiles = (fileList: FileList | File[]) => {
    addFiles(fileList);
    if (autoUpload()) {
      queueMicrotask(() => upload());
    }
  };

  const onDrop = (e: DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    if (e.dataTransfer?.files.length) {
      handleFiles(e.dataTransfer.files);
    }
  };

  const onInputChange = (e: Event) => {
    const input = e.target as HTMLInputElement;
    if (input.files?.length) {
      handleFiles(input.files);
      input.value = "";
    }
  };

  return (
    <div style={{ display: "contents" }}>
      {props.trigger ? (
        props.trigger({ open })
      ) : (
        <button type="button" class="bunny-widget-trigger" onClick={open}>
          {label()}
        </button>
      )}

      <Show when={isOpen()}>
        <dialog
          ref={(el) => {
            dialogRef = el;
            // showModal on next microtask after DOM insertion
            queueMicrotask(() => el.showModal());
          }}
          class="bunny-widget-dialog"
          onClose={close}
          onClick={(e) => {
            if (e.target === dialogRef) close();
          }}
        >
          <div class="bunny-widget">
            <div class="bunny-widget-header">
              <span class="bunny-widget-title">{label()}</span>
              <button
                type="button"
                class="bunny-widget-close"
                onClick={close}
                aria-label="Close"
              >
                &times;
              </button>
            </div>

            <div
              class={`bunny-widget-dropzone ${isDragOver() ? "bunny-widget-dropzone--active" : ""}`}
              onDrop={onDrop}
              onDragOver={(e) => {
                e.preventDefault();
                setIsDragOver(true);
              }}
              onDragLeave={(e) => {
                e.preventDefault();
                setIsDragOver(false);
              }}
              onClick={() => inputRef?.click()}
              role="button"
              tabIndex={0}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") inputRef?.click();
              }}
            >
              <input
                ref={inputRef!}
                type="file"
                multiple={props.maxFiles !== 1}
                accept={props.accept?.join(",")}
                onChange={onInputChange}
                style={{ display: "none" }}
              />
              <p class="bunny-widget-dropzone-text">
                {isDragOver()
                  ? "Drop to upload"
                  : "Drop files here or click to browse"}
              </p>
              <Show when={props.maxSize != null}>
                <p class="bunny-widget-hint">
                  Max{" "}
                  {typeof props.maxSize === "string"
                    ? props.maxSize
                    : formatBytes(props.maxSize as number)}
                  {props.maxFiles
                    ? ` · ${props.maxFiles} file${props.maxFiles > 1 ? "s" : ""}`
                    : ""}
                </p>
              </Show>
            </div>

            <Show when={files().length > 0}>
              <ul class="bunny-widget-file-list">
                <For each={files()}>
                  {(file) => (
                    <li class={`bunny-widget-file bunny-widget-file--${file.status}`}>
                      <span class="bunny-widget-file-name">{file.name}</span>
                      <span class="bunny-widget-file-size">
                        {formatBytes(file.size)}
                      </span>

                      <Show when={file.status === "uploading"}>
                        <div class="bunny-widget-progress">
                          <div
                            class="bunny-widget-progress-bar"
                            style={{ width: `${file.progress}%` }}
                          />
                        </div>
                      </Show>

                      <Show when={file.status === "complete"}>
                        <span class="bunny-widget-file-complete">✓</span>
                      </Show>

                      <Show when={file.status === "error"}>
                        <span class="bunny-widget-file-error">
                          {file.error ?? "Failed"}
                        </span>
                      </Show>

                      <Show
                        when={
                          file.status === "idle" || file.status === "error"
                        }
                      >
                        <button
                          class="bunny-widget-file-remove"
                          onClick={() => removeFile(file.id)}
                          aria-label={`Remove ${file.name}`}
                        >
                          &times;
                        </button>
                      </Show>
                    </li>
                  )}
                </For>
              </ul>
            </Show>

            <div class="bunny-widget-footer">
              <Show
                when={
                  !autoUpload() &&
                  files().some((f) => f.status === "idle")
                }
              >
                <button
                  type="button"
                  class="bunny-widget-upload"
                  onClick={() => upload()}
                  disabled={isUploading()}
                >
                  {isUploading() ? "Uploading..." : "Upload"}
                </button>
              </Show>
              <Show when={allComplete()}>
                <button
                  type="button"
                  class="bunny-widget-done"
                  onClick={close}
                >
                  Done
                </button>
              </Show>
            </div>
          </div>
        </dialog>
      </Show>
    </div>
  );
}

// packages/react/src/upload-widget.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import type { FileState, UploadResult } from "@bunny.net/upload-core";
import { formatBytes } from "@bunny.net/upload-core";
import { useBunnyUpload } from "./use-bunny-upload";

export interface UploadWidgetProps {
  endpoint?: string;
  accept?: string[];
  maxSize?: string | number;
  maxFiles?: number;
  onComplete?: (files: UploadResult[]) => void;
  onError?: (error: Error, file?: FileState) => void;
  autoUpload?: boolean;
  /** Label for the trigger button */
  label?: string;
  /** Custom trigger element — receives `open` function */
  trigger?: (props: { open: () => void }) => React.ReactNode;
}

export function UploadWidget({
  endpoint,
  accept,
  maxSize,
  maxFiles,
  onComplete,
  onError,
  autoUpload = true,
  label = "Upload files",
  trigger,
}: UploadWidgetProps) {
  const [isOpen, setIsOpen] = useState(false);
  const { files, addFiles, removeFile, upload, reset, isUploading } =
    useBunnyUpload({ endpoint, accept, maxSize, maxFiles, onComplete, onError });

  const inputRef = useRef<HTMLInputElement>(null);
  const [isDragOver, setIsDragOver] = useState(false);
  const dialogRef = useRef<HTMLDialogElement>(null);

  const open = useCallback(() => setIsOpen(true), []);
  const close = useCallback(() => {
    setIsOpen(false);
    reset();
  }, [reset]);

  useEffect(() => {
    if (isOpen) {
      dialogRef.current?.showModal();
    } else {
      dialogRef.current?.close();
    }
  }, [isOpen]);

  const handleFiles = useCallback(
    (fileList: FileList | File[]) => {
      addFiles(fileList);
      if (autoUpload) {
        queueMicrotask(() => upload());
      }
    },
    [addFiles, autoUpload, upload]
  );

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragOver(false);
      if (e.dataTransfer.files.length > 0) {
        handleFiles(e.dataTransfer.files);
      }
    },
    [handleFiles]
  );

  const acceptString = accept?.join(",");
  const allComplete = files.length > 0 && files.every((f) => f.status === "complete");

  return (
    <>
      {trigger ? (
        trigger({ open })
      ) : (
        <button type="button" className="bunny-widget-trigger" onClick={open}>
          {label}
        </button>
      )}

      {isOpen && (
        <dialog
          ref={dialogRef}
          className="bunny-widget-dialog"
          onClose={close}
          onClick={(e) => {
            if (e.target === dialogRef.current) close();
          }}
        >
          <div className="bunny-widget">
            <div className="bunny-widget-header">
              <span className="bunny-widget-title">{label}</span>
              <button
                type="button"
                className="bunny-widget-close"
                onClick={close}
                aria-label="Close"
              >
                &times;
              </button>
            </div>

            <div
              className={`bunny-widget-dropzone ${isDragOver ? "bunny-widget-dropzone--active" : ""}`}
              onDrop={handleDrop}
              onDragOver={(e) => {
                e.preventDefault();
                setIsDragOver(true);
              }}
              onDragLeave={(e) => {
                e.preventDefault();
                setIsDragOver(false);
              }}
              onClick={() => inputRef.current?.click()}
              role="button"
              tabIndex={0}
              onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ")
                  inputRef.current?.click();
              }}
            >
              <input
                ref={inputRef}
                type="file"
                multiple={maxFiles !== 1}
                accept={acceptString}
                onChange={(e) => {
                  if (e.target.files?.length) {
                    handleFiles(e.target.files);
                    e.target.value = "";
                  }
                }}
                style={{ display: "none" }}
              />
              <p className="bunny-widget-dropzone-text">
                {isDragOver
                  ? "Drop to upload"
                  : "Drop files here or click to browse"}
              </p>
              {maxSize && (
                <p className="bunny-widget-hint">
                  Max{" "}
                  {typeof maxSize === "string"
                    ? maxSize
                    : formatBytes(maxSize)}
                  {maxFiles && ` · ${maxFiles} file${maxFiles > 1 ? "s" : ""}`}
                </p>
              )}
            </div>

            {files.length > 0 && (
              <ul className="bunny-widget-file-list">
                {files.map((file) => (
                  <li
                    key={file.id}
                    className={`bunny-widget-file bunny-widget-file--${file.status}`}
                  >
                    <span className="bunny-widget-file-name">{file.name}</span>
                    <span className="bunny-widget-file-size">
                      {formatBytes(file.size)}
                    </span>

                    {file.status === "uploading" && (
                      <div className="bunny-widget-progress">
                        <div
                          className="bunny-widget-progress-bar"
                          style={{ width: `${file.progress}%` }}
                        />
                      </div>
                    )}

                    {file.status === "complete" && (
                      <span className="bunny-widget-file-complete">✓</span>
                    )}

                    {file.status === "error" && (
                      <span className="bunny-widget-file-error">
                        {file.error ?? "Failed"}
                      </span>
                    )}

                    {(file.status === "idle" || file.status === "error") && (
                      <button
                        className="bunny-widget-file-remove"
                        onClick={() => removeFile(file.id)}
                        aria-label={`Remove ${file.name}`}
                      >
                        &times;
                      </button>
                    )}
                  </li>
                ))}
              </ul>
            )}

            <div className="bunny-widget-footer">
              {!autoUpload && files.some((f) => f.status === "idle") && (
                <button
                  type="button"
                  className="bunny-widget-upload"
                  onClick={() => upload()}
                  disabled={isUploading}
                >
                  {isUploading ? "Uploading..." : "Upload"}
                </button>
              )}
              {allComplete && (
                <button
                  type="button"
                  className="bunny-widget-done"
                  onClick={close}
                >
                  Done
                </button>
              )}
            </div>
          </div>
        </dialog>
      )}
    </>
  );
}
