// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  BunnyUpload,
  UploadWidget,
  UploadDropzone,
  UploadFileList,
  useBunnyUpload,
  formatBytes,
  type UploadResult,
  type FileState,
} from "@bunny.net/upload-vue";

// For the hook example
const {
  files: hookFiles,
  addFiles,
  removeFile: hookRemoveFile,
  upload: hookUpload,
  reset: hookReset,
  isUploading: hookIsUploading,
} = useBunnyUpload({
  accept: ["image/*"],
  maxSize: "10mb",
  maxFiles: 5,
  onComplete: (files) => console.log("Hook uploaded:", files),
});

const hookInputRef = ref<HTMLInputElement | null>(null);
</script>

<template>
  <main>
    <h1>Bunny Upload — Vue</h1>

    <section>
      <h2>Simple Button</h2>
      <p>Pick a file and see its name + upload status inline.</p>
      <BunnyUpload
        :accept="['image/*']"
        max-size="10mb"
        @complete="(files: UploadResult[]) => console.log('Uploaded:', files)"
      />
    </section>

    <section>
      <h2>Upload Widget</h2>
      <p>A button that opens a modal with dropzone, file list, and progress.</p>
      <UploadWidget
        :accept="['image/*']"
        max-size="10mb"
        :max-files="5"
        @complete="(files: UploadResult[]) => console.log('Uploaded:', files)"
      />
    </section>

    <section>
      <h2>Custom Dropzone</h2>
      <p>Full control over the UI with scoped slots.</p>
      <UploadDropzone
        :accept="['image/*']"
        max-size="10mb"
        :max-files="5"
        @complete="(files: UploadResult[]) => console.log('Uploaded:', files)"
      >
        <template #default="{ isDragOver, openFilePicker, files, removeFile, getDropzoneProps }">
          <div>
            <div
              v-bind="getDropzoneProps()"
              @click="openFilePicker"
              :style="{
                border: `2px dashed ${isDragOver ? '#f60' : '#ccc'}`,
                borderRadius: '8px',
                padding: '40px',
                textAlign: 'center',
                cursor: 'pointer',
                background: isDragOver ? '#fff8f0' : 'transparent',
                transition: 'all 0.2s',
              }"
            >
              <p>{{ isDragOver ? "Drop to upload" : "Drag images here or click to browse" }}</p>
            </div>

            <ul v-if="files.length > 0" style="list-style: none; padding: 0; margin-top: 16px">
              <li
                v-for="file in files"
                :key="file.id"
                style="display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee"
              >
                <span>
                  <strong>{{ file.name }}</strong>
                  <span style="color: #888; margin-left: 8px">{{ formatBytes(file.size) }}</span>
                </span>
                <span>
                  <template v-if="file.status === 'uploading'">{{ Math.round(file.progress) }}%</template>
                  <template v-if="file.status === 'complete'">✓</template>
                  <template v-if="file.status === 'error'">
                    <span style="color: red">{{ file.error }}</span>
                  </template>
                  <button
                    v-if="file.status === 'idle' || file.status === 'error'"
                    @click="removeFile(file.id)"
                    style="margin-left: 8px; cursor: pointer"
                  >×</button>
                </span>
              </li>
            </ul>
          </div>
        </template>
      </UploadDropzone>
    </section>

    <section>
      <h2>Headless Composable</h2>
      <p>Maximum control — just the state and methods, zero UI from us.</p>
      <div style="display: flex; gap: 8px">
        <label style="display: inline-block; padding: 8px 16px; border: 1px solid #ccc; border-radius: 4px; cursor: pointer">
          Add files
          <input
            ref="hookInputRef"
            type="file"
            multiple
            accept="image/*"
            @change="(e: Event) => {
              const input = e.target as HTMLInputElement;
              if (input.files?.length) {
                addFiles(input.files);
                input.value = '';
              }
            }"
            style="display: none"
          />
        </label>
        <button @click="hookUpload()" :disabled="hookIsUploading || hookFiles.length === 0" style="padding: 8px 16px">
          {{ hookIsUploading ? 'Uploading...' : 'Upload' }}
        </button>
        <button @click="hookReset()" :disabled="hookFiles.length === 0" style="padding: 8px 16px">
          Reset
        </button>
      </div>

      <UploadFileList
        :files="hookFiles"
        @remove="hookRemoveFile"
        @retry="hookUpload()"
      />
    </section>
  </main>
</template>

<style scoped>
main {
  max-width: 640px;
  margin: 40px auto;
  padding: 0 20px;
}
section {
  margin-top: 40px;
}
section p {
  color: #666;
  margin-bottom: 16px;
}
</style>

// examples/nextjs-i18n/app/page.tsx
"use client";

import { useState } from "react";
import {
  BunnyUpload,
  UploadWidget,
  UploadFileList,
  useBunnyUpload,
  defaultLocale,
  type BunnyUploadLocale,
} from "@bunny.net/upload-react";
import { de } from "./locales/de";
import { es } from "./locales/es";
import { ja } from "./locales/ja";

const locales: Record<string, { label: string; locale: BunnyUploadLocale }> = {
  en: { label: "English", locale: defaultLocale },
  de: { label: "Deutsch", locale: de },
  es: { label: "Español", locale: es },
  ja: { label: "日本語", locale: ja },
};

export default function Home() {
  const [lang, setLang] = useState("en");
  const current = locales[lang].locale;

  return (
    <main style={{ maxWidth: 640, margin: "40px auto", padding: "0 20px" }}>
      <h1>Bunny Upload — i18n</h1>
      <p style={{ color: "#666" }}>
        Switch languages to see all component strings update.
      </p>

      <div style={{ display: "flex", gap: 8, margin: "24px 0" }}>
        {Object.entries(locales).map(([key, { label }]) => (
          <button
            key={key}
            onClick={() => setLang(key)}
            style={{
              padding: "8px 16px",
              borderRadius: 6,
              border: lang === key ? "2px solid #f60" : "1px solid #ccc",
              background: lang === key ? "#fff8f0" : "white",
              cursor: "pointer",
              fontWeight: lang === key ? 600 : 400,
            }}
          >
            {label}
          </button>
        ))}
      </div>

      <Section
        title="Simple Button"
        description="The button label, status text, and overflow count are all localized."
      >
        <BunnyUpload
          accept={["image/*"]}
          maxSize="10mb"
          locale={current}
          onComplete={(files) => console.log("Uploaded:", files)}
        />
      </Section>

      <Section
        title="Upload Widget"
        description="Dropzone text, tab labels, progress labels, buttons, and ARIA labels."
      >
        <UploadWidget
          accept={["image/*"]}
          maxSize="10mb"
          maxFiles={5}
          locale={current}
          onComplete={(files) => console.log("Uploaded:", files)}
        />
      </Section>

      <Section
        title="Upload Widget + File Manager"
        description="Browse tab, file manager strings, selection count, and folder prompts."
      >
        <UploadWidget
          accept={["image/*"]}
          maxSize="10mb"
          maxFiles={5}
          withFileManager
          locale={current}
          onComplete={(files) => console.log("Selected:", files)}
        />
      </Section>

      <Section
        title="Partial Override"
        description="You can override just a few strings instead of providing a full locale."
      >
        <UploadWidget
          accept={["image/*"]}
          maxSize="10mb"
          locale={{
            uploadFiles: "Upload photos",
            dropOrBrowse: "Drag your photos here",
            dropToUpload: "Release to upload photos",
            done: "All done!",
          }}
          onComplete={(files) => console.log("Uploaded:", files)}
        />
      </Section>

      <Section
        title="Headless Hook + UploadFileList"
        description="Locale is passed to UploadFileList for status text and ARIA labels."
      >
        <HookExample locale={current} />
      </Section>
    </main>
  );
}

function Section({
  title,
  description,
  children,
}: {
  title: string;
  description: string;
  children: React.ReactNode;
}) {
  return (
    <section style={{ marginTop: 40 }}>
      <h2>{title}</h2>
      <p style={{ color: "#666", marginBottom: 16 }}>{description}</p>
      {children}
    </section>
  );
}

function HookExample({ locale }: { locale: BunnyUploadLocale }) {
  const { files, addFiles, removeFile, upload, reset, isUploading } =
    useBunnyUpload({
      accept: ["image/*"],
      maxSize: "10mb",
      maxFiles: 5,
      onComplete: (files) => console.log("Uploaded:", files),
    });

  return (
    <div>
      <div style={{ display: "flex", gap: 8 }}>
        <label
          style={{
            display: "inline-block",
            padding: "8px 16px",
            border: "1px solid #ccc",
            borderRadius: 4,
            cursor: "pointer",
          }}
        >
          {locale.chooseFile}
          <input
            type="file"
            multiple
            accept="image/*"
            onChange={(e) => {
              if (e.target.files?.length) {
                addFiles(e.target.files);
                e.target.value = "";
              }
            }}
            style={{ display: "none" }}
          />
        </label>
        <button
          onClick={() => upload()}
          disabled={isUploading || files.length === 0}
          style={{ padding: "8px 16px" }}
        >
          {isUploading ? locale.uploading : locale.upload}
        </button>
        <button
          onClick={reset}
          disabled={files.length === 0}
          style={{ padding: "8px 16px" }}
        >
          Reset
        </button>
      </div>

      <UploadFileList
        files={files}
        onRemove={removeFile}
        onRetry={() => upload()}
        locale={locale}
      />
    </div>
  );
}
